### ISSUE TITLE
Investigate/fix mobile's test_sort_by_region test (reliability/speed)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#738] opened 2015-01-08 01:36 UTC
The runtime of amo.prod.mobile.saucelabs varied widely, in no small part due to:

test_sort_by_region, from here:

https://github.com/mozilla/Addon-Tests/blob/master/tests/mobile/test_extensions.py#L17

Stack: self = <tests.mobile.test_extensions.TestExtensions instance at 0x1048f8320>
mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x1036bbcf8>

    @pytest.mark.nondestructive
    def test_sort_by_region(self, mozwebqa):
    
        home = Home(mozwebqa)
>       extensions_page = home.click_all_featured_addons_link()

tests/mobile/test_extensions.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pages.mobile.home.Home object at 0x1048c8750>

    def click_all_featured_addons_link(self):
        self.selenium.find_element(*self._all_featured_addons_locator).click()
        from pages.mobile.extensions import Extensions
        extensions_page = Extensions(self.testsetup)
>       WebDriverWait(self.selenium, self.timeout).until(lambda s: self.is_element_visible(*extensions_page._sort_by_locator))

pages/mobile/home.py:91: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.support.wait.WebDriverWait object at 0x103670d10>
method = <function <lambda> at 0x1048ff6e0>, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        end_time = time.time() + self._timeout
        while(True):
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions:
                pass
            time.sleep(self._poll)
            if(time.time() > end_time):
                break
>       raise TimeoutException(message)
E       TimeoutException: Message:

.env/lib/python2.7/site-packages/selenium/webdriver/support/wait.py:71: TimeoutException

Sauce Labs job: https://saucelabs.com/tests/3ae1ca626598433d8cd4d0511f3d98a7

**Comment by stephendonner** [comment] 2015-01-08 01:39
Even when it "passes" (after many reruns from our plugin), the runtimes themselves widely vary, as such:

http://selenium.qa.mtv2.mozilla.com:8080/view/AMO/job/amo.prod.mobile.saucelabs/buildTimeTrend

Questions:
* is this us?
* is this Sauce Labs?
* or a confluence of both?

<img src="http://imgur.com/HZHBbJX"></img>

**Comment by stephendonner** [comment] 2015-01-09 02:04
@bobsilverberg can you take a look at this when you get a chance?  Thx!

**Comment by bobsilverberg** [comment] 2015-01-09 19:08
Sure, @stephendonner, I will put it on my ToDo list. I'm trying to get through PR reviews today so it may not be until next week.

**Comment by bobsilverberg** [comment] 2015-01-09 20:25
I took a look at the test results and there's a pretty obvious correlation between the run times and whether tests are being rerun. That is, when there are no reruns then the jobs finish in around 1 minute. The jobs that completed in 4-15 minutes all had some reruns. Some had one test rerun, some had a number. 

The ones that failed with a timeout, usually after 22 minutes, all include a failure of `TestExtensions.test_sort_by_region`, so that's definitely a test that we should look at to see if we can improve it. The failed runs occasionally include reruns of other tests, but the one that always fails is `TestExtensions.test_sort_by_region`.

@AndreiH Do you think you can take a look at that specific test on Monday to see if there is any room for improvement?

**Comment by AndreiH** [comment] 2015-01-12 10:44
I run the test locally and it failed for me 9/10 times. The reason those builds take that much longer is because it took <code>test_sort_by_region</code> like 3 minutes before it failed when I tested this.
It makes sense with all those reruns. 
I could reproduce this easily when running that test on Sauce. The test just needed a fix with scroll into view (see PR https://github.com/mozilla/Addon-Tests/pull/740).
After adding this I could not reproduce the fail anymore test is passing 15/15 runs

**Comment by bobsilverberg** [comment] 2015-01-13 14:38
It looks like this has been addressed via PR #740. The test is passing well now, and quickly. I am submitted a few runs of the job so we can see if it is consistently fast.

http://selenium.qa.mtv2.mozilla.com:8080/view/AMO/job/amo.dev.mobile.saucelabs/buildTimeTrend

**Comment by bobsilverberg** [comment] 2015-01-13 14:38
@stephendonner I will leave this to you to close when you are confident that the issue has been addressed.

**Comment by AndreiH** [comment] 2015-01-16 09:35
This was fixed. Closing this. Thanks!

**Closed by AndreiH** 2015-01-16 09:35 UTC
Labels: difficulty intermediate, priority high, Test Failure
